# Generated by Django 5.0.6 on 2024-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(max_length=255),
        ),
    ]
