# Generated by Django 5.0.6 on 2024-06-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
    ]
